/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class happydns_JniBridge */

#ifndef _Included_happydns_JniBridge
#define _Included_happydns_JniBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     happydns_JniBridge
 * Method:    setJniCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_happydns_JniBridge_setJniCallback
  (JNIEnv *, jobject);

/*
 * Class:     happydns_JniBridge
 * Method:    test
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_happydns_JniBridge_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif